services:
  - type: web
    name: analisador-milhar
    env: python
    buildCommand: |
      apt-get update && apt-get install -y poppler-utils tesseract-ocr
      pip install -r requirements.txt
    startCommand: gunicorn app:app

